# Generated by Django 3.1.4 on 2020-12-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201208_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemnotice',
            old_name='create_time',
            new_name='start_time',
        ),
    ]
