# Generated by Django 3.1.4 on 2020-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201208_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.TextField(blank=True, null=True, verbose_name='头像地址'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='现居城市'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nick',
            field=models.CharField(blank=True, max_length=64, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='vertify',
            field=models.IntegerField(blank=True, max_length=32, null=True, verbose_name='验证码'),
        ),
    ]
