# Generated by Django 3.1.4 on 2020-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201209_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='vertify',
            field=models.IntegerField(blank=True, null=True, verbose_name='验证码'),
        ),
    ]
