# Generated by Django 3.1.4 on 2020-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201209_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nick',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='昵称'),
        ),
    ]
