# Generated by Django 4.1 on 2023-12-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_token', models.CharField(default='', max_length=128, verbose_name='平台token')),
            ],
        ),
        migrations.AddField(
            model_name='runinfo',
            name='token',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MonitorService.platformtoken'),
        ),
    ]
