# Generated by Django 4.1 on 2023-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0002_platformtoken_runinfo_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtoken',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
