# Generated by Django 4.1 on 2023-12-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0003_platformtoken_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_cookies', models.CharField(default='', max_length=128, verbose_name='平台cookies')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='runinfo',
            name='token',
        ),
        migrations.DeleteModel(
            name='PlatformToken',
        ),
        migrations.AddField(
            model_name='runinfo',
            name='cookies',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MonitorService.platformcookies'),
        ),
    ]
