# Generated by Django 4.1 on 2023-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0004_platformcookies_remove_runinfo_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcookies',
            name='platform_url',
            field=models.CharField(default='', max_length=128, verbose_name='平台cookies'),
        ),
    ]
