# Generated by Django 4.1 on 2023-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0005_platformcookies_platform_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcookies',
            name='platform_url',
            field=models.CharField(default='', max_length=128, verbose_name='平台url'),
        ),
    ]
