# Generated by Django 4.1 on 2023-12-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0006_alter_platformcookies_platform_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcookies',
            name='platform_name',
            field=models.CharField(default='', max_length=128, verbose_name='平台名称'),
        ),
    ]
