# Generated by Django 4.1 on 2023-12-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0007_platformcookies_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runinfo',
            name='platform_name',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='平台名称'),
        ),
    ]
