# Generated by Django 4.1 on 2023-12-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorService', '0008_alter_runinfo_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcookies',
            name='platform_name',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='平台名称'),
        ),
    ]
